language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7.0
  - 7.1
  - 7.2
matrix:
  include:
    - php: 5.2
      dist: precise
    - php: 5.3
      dist: precise


install:
  - composer install

script:
  - ./vendor/phpunit/phpunit/phpunit tests/TestUserAgent.php
